import * as path from 'path';
import * as vscode from 'vscode';
import {
    AgentSyncPaths,
    ensureDir,
    fileExists,
    readFile,
    writeFile,
    appendToFile,
} from '../services/fileService';
import { log } from '../utils/logger';

// Files to always include if they exist
const KEY_FILES = [
    'package.json',
    'pyproject.toml',
    'requirements.txt',
    'pom.xml',
    'build.gradle',
    'Cargo.toml',
    'go.mod',
    'composer.json',
    'README.md',
    '.github/copilot-instructions.md',
    'AGENTS.md',
    'CLAUDE.md',
    'GEMINI.md',
    'tsconfig.json',
    '.eslintrc.json',
    '.eslintrc.js',
    'jest.config.js',
    'jest.config.ts',
    'vite.config.ts',
    'webpack.config.js',
    'docker-compose.yml',
    'Dockerfile',
];

// Source globs to sample (max 8 files, 60 lines each)
const SOURCE_GLOBS = [
    'src/**/*.{ts,js,tsx,jsx}',
    'src/**/*.{py,java,cs,go,rs}',
    'app/**/*.{ts,js,py}',
    'lib/**/*.{ts,js}',
];

const EXCLUDE_DIRS = '{**/node_modules/**,**/.git/**,**/dist/**,**/out/**,**/.agent-sync/**,**/build/**,**/__pycache__/**}';

function truncateLines(text: string, max: number): string {
    const lines = text.split('\n');
    return lines.length <= max
        ? text
        : lines.slice(0, max).join('\n') + `\n… (${lines.length - max} more lines)`;
}

async function gatherSnapshot(workspaceRoot: string): Promise<string> {
    const parts: string[] = [];

    // 1. File tree (paths only)
    const allFiles = await vscode.workspace.findFiles('**/*', EXCLUDE_DIRS, 300);
    const tree = allFiles
        .map(f => path.relative(workspaceRoot, f.fsPath).replace(/\\/g, '/'))
        .sort()
        .join('\n');
    parts.push(`## File Tree\n\`\`\`\n${tree}\n\`\`\``);

    // 2. Key files
    const keyParts: string[] = [];
    for (const rel of KEY_FILES) {
        const full = path.join(workspaceRoot, rel);
        if (await fileExists(full)) {
            const raw = await readFile(full);
            if (!raw.trim()) { continue; }
            const maxLines = rel === 'README.md' ? 80 : 200;
            keyParts.push(`### \`${rel}\`\n\`\`\`\n${truncateLines(raw, maxLines)}\n\`\`\``);
        }
    }

    // Also scan *.instructions.md
    const instrFiles = await vscode.workspace.findFiles('**/*.instructions.md', EXCLUDE_DIRS, 10);
    for (const uri of instrFiles) {
        const rel = path.relative(workspaceRoot, uri.fsPath).replace(/\\/g, '/');
        if (rel.includes('copilot-instructions')) { continue; }
        const raw = await readFile(uri.fsPath);
        if (raw.trim()) {
            keyParts.push(`### \`${rel}\`\n\`\`\`\n${truncateLines(raw, 100)}\n\`\`\``);
        }
    }

    if (keyParts.length > 0) {
        parts.push(`## Key Files\n\n${keyParts.join('\n\n')}`);
    }

    // 3. Sample source files
    const srcParts: string[] = [];
    let srcCount = 0;
    for (const glob of SOURCE_GLOBS) {
        if (srcCount >= 8) { break; }
        const found = await vscode.workspace.findFiles(glob, EXCLUDE_DIRS, 5);
        for (const uri of found) {
            if (srcCount >= 8) { break; }
            const rel = path.relative(workspaceRoot, uri.fsPath).replace(/\\/g, '/');
            const raw = await readFile(uri.fsPath);
            if (!raw.trim()) { continue; }
            srcParts.push(`### \`${rel}\`\n\`\`\`\n${truncateLines(raw, 60)}\n\`\`\``);
            srcCount++;
        }
    }
    if (srcParts.length > 0) {
        parts.push(`## Source File Samples\n\n${srcParts.join('\n\n')}`);
    }

    return parts.join('\n\n');
}

function buildPrompt(snapshot: string, today: string): string {
    return `You are an expert software engineering assistant. Analyze the following workspace snapshot and generate a comprehensive \`context.md\` file that will be used to synchronize AI agent context across machines.

The context.md MUST follow this exact structure and be as detailed and specific as possible based on the available information:

\`\`\`markdown
# Agent Context

> Auto-generated by Agent Sync for Copilot on ${today}. Review and refine as needed.

---

## Project Overview
<Detailed description: purpose, tech stack, language versions, framework, repo links if visible>

## Current Goals
<Active work areas inferred from scripts, recent files, README — bullet points with checkboxes>

## Key Architecture Decisions
| Date | Decision | Rationale |
|------|----------|-----------|
| ${today} | <key design choice inferred from stack/config> | <rationale> |

## Known Issues / Bugs
<Any issues mentioned in README, TODOs in code, or "None identified.">

## Next Tasks
<Infer from README, package.json scripts, project structure — numbered list>

## Tech Stack
<Precise: language + version, framework + version, key dependencies with versions, build tool, test framework, CI/CD if visible>

## Project Structure
<Describe each main folder and its purpose based on the file tree>

## Decisions Log

\`\`\`

Rules:
- Use ACTUAL file names, package names, and version numbers from the provided data.
- Do NOT invent information — if something truly cannot be inferred, write "Not determined."
- Be specific and concise. No filler sentences.
- Output ONLY the markdown content. No explanation, no preamble, no code fences around the whole output.

---

## Workspace Snapshot

${snapshot}`;
}

export async function aiCaptureContext(
    workspaceRoot: string,
    secrets: vscode.SecretStorage,
    cancellationToken?: vscode.CancellationToken,
    streamOutput?: vscode.ChatResponseStream
): Promise<string | null> {
    const contextPath = AgentSyncPaths.context(workspaceRoot);
    const historyPath = AgentSyncPaths.history(workspaceRoot);
    const token = cancellationToken ?? new vscode.CancellationTokenSource().token;

    // Confirm overwrite if context.md already has content
    if (!streamOutput && await fileExists(contextPath)) {
        const existing = await readFile(contextPath);
        if (existing.trim().length > 200) {
            const choice = await vscode.window.showWarningMessage(
                'Agent Sync: context.md already has content. Overwrite with AI-generated context?',
                { modal: true },
                'Overwrite',
                'Cancel'
            );
            if (choice !== 'Overwrite') { return null; }
        }
    }

    // Select LM
    let model: vscode.LanguageModelChat;
    try {
        const models = await vscode.lm.selectChatModels({ vendor: 'copilot', family: 'gpt-4o' });
        if (!models.length) {
            const fallback = await vscode.lm.selectChatModels({ vendor: 'copilot' });
            if (!fallback.length) {
                throw new Error('No Copilot language model available. Make sure GitHub Copilot is installed and signed in.');
            }
            model = fallback[0];
        } else {
            model = models[0];
        }
    } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        if (!streamOutput) {
            vscode.window.showErrorMessage(`Agent Sync: ${msg}`);
        }
        log(`ERROR aiCaptureContext — model selection: ${msg}`);
        return null;
    }

    const today = new Date().toISOString().slice(0, 10);
    let snapshot = '';
    let generated = '';

    const run = async (progress?: vscode.Progress<{ message?: string }>) => {
        progress?.report({ message: 'Reading workspace files…' });
        streamOutput?.progress('Reading workspace files…');
        log('aiCaptureContext: gathering workspace snapshot…');

        snapshot = await gatherSnapshot(workspaceRoot);
        const prompt = buildPrompt(snapshot, today);

        progress?.report({ message: 'Asking Copilot to generate context…' });
        streamOutput?.progress('Asking Copilot to analyze the workspace…');
        log(`aiCaptureContext: sending ${prompt.length} chars to LM (model: ${model.name})…`);

        const messages = [vscode.LanguageModelChatMessage.User(prompt)];
        const response = await model.sendRequest(messages, {}, token);

        for await (const chunk of response.text) {
            generated += chunk;
            // Stream to chat output if available
            streamOutput?.markdown(chunk);
        }

        if (!generated.trim()) {
            throw new Error('The language model returned an empty response.');
        }

        progress?.report({ message: 'Saving context.md…' });
        await ensureDir(AgentSyncPaths.dir(workspaceRoot));
        await writeFile(contextPath, generated);

        const ts = new Date().toISOString();
        const record = JSON.stringify({
            ts,
            type: 'ai_context_captured',
            text: `AI-generated context via ${model.name} — ${generated.split('\n').length} lines`,
        });
        await appendToFile(historyPath, record + '\n');
        log(`aiCaptureContext: wrote ${generated.split('\n').length} lines to context.md`);
    };

    if (streamOutput) {
        // Running inside chat participant — no progress notification
        try {
            await run();
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            log(`ERROR aiCaptureContext: ${msg}`);
            streamOutput.markdown(`\n\n**Error:** ${msg}`);
            return null;
        }
    } else {
        // Running as a command — show progress notification
        let errorMsg: string | null = null;
        await vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: 'Agent Sync: AI capturing workspace context…',
                cancellable: false,
            },
            async (progress) => {
                try {
                    await run(progress);
                } catch (err) {
                    errorMsg = err instanceof Error ? err.message : String(err);
                }
            }
        );
        if (errorMsg) {
            vscode.window.showErrorMessage(`Agent Sync: AI capture failed — ${errorMsg}`);
            log(`ERROR aiCaptureContext: ${errorMsg}`);
            return null;
        }

        // Offer to push
        const action = await vscode.window.showInformationMessage(
            `Agent Sync: context.md generated by Copilot (${generated.split('\n').length} lines). Push to cloud now?`,
            'Push to Cloud',
            'Open context.md',
            'Dismiss'
        );
        if (action === 'Push to Cloud') {
            await vscode.commands.executeCommand('agentSync.generateSummary');
            await vscode.commands.executeCommand('agentSync.cloudPush');
        } else if (action === 'Open context.md') {
            const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(contextPath));
            await vscode.window.showTextDocument(doc);
        }
    }

    return generated;
}
