const TODAY = new Date().toISOString().slice(0, 10);

export const CONTEXT_MD_TEMPLATE = `# Agent Context

> Managed by Agent Sync for Copilot. Edit freely — this file is your persistent project memory.

---

## Project Overview

<!-- Describe the project: purpose, stack, team, repo links. -->

## Current Goals

<!-- What are you actively working on right now? Bullet points work well. -->

- [ ] Goal 1
- [ ] Goal 2

## Key Architecture Decisions

<!-- Record significant design choices and their rationale. -->

| Date | Decision | Rationale |
|------|----------|-----------|
| ${TODAY} | Initial setup | Project kickoff |

## Known Issues / Bugs

<!-- Active issues, debugged but unresolved items, workarounds. -->

- None yet.

## Next Tasks

<!-- Ordered list of upcoming work items. -->

1. Complete project setup
2. Define architecture

## Decisions Log

<!-- Auto-populated by "Append Decision" command. Do not edit manually. -->

`;

export const SUMMARY_MD_TEMPLATE = `# Agent Summary

> Auto-generated by Agent Sync. Use "Copy Summary to Clipboard" and paste into Copilot Chat.

*Not yet generated. Run "Agent Sync: Generate Summary" to populate this file.*
`;

export const HISTORY_JSONL_TEMPLATE = '';

export const CONFIG_JSON_TEMPLATE = JSON.stringify(
    {
        maxSummaryLines: 50,
        autoGenerateSummaryOnSave: true,
        includeWorkspaceFiles: false,
    },
    null,
    2
);
